### ISSUE TITLE
Export option not working

### ISSUE THREAD

**Issue by Leptopoda** [sammerk/Sitzung_1_synchron#1]
I assume the PDF-Export mode in the options is meant to export the slides into a PDF (duh)
Both Firefox (106-Linux, 105-Windows) and Chromium (106-Linux) don't do anything when trying to use the export mode.
On Chrome at least it does something (sorta overlays all slides onto one and then revert back to a single slide). On Firefox this only triggers the slides overview mode.

If the export option is not meant to export the Slides it'd be helpful to have such an option.

EDIT: looks like the export option will generate a page better suited to be used with the browser print tool. In this case the print dialog should triggered automatically or an event listener should be registered that will generate the print version when the user tries to print the page.
https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeprint_event

**Comment by Leptopoda** [comment]
Ok a fast little update:
judging from the libs the framework used is slides.js so I opened an [issue](https://github.com/hakimel/reveal.js/issues/3300) over there as it's probably an FR for them.

**Comment by sammerk** [comment]
Great! Seems to me like you l´knwo much more about web dev stuff than me 🤣. I’m just using the quarto defaults for revealJS …
Best
Samuel
